// <auto-generated />
namespace Session7_VideoRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202104010024199_initial-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
